name: Build IPA
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Theos & SDK
        run: |
          sudo apt update
          sudo apt install -y git make clang lld unzip
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          wget -O sdks.zip https://github.com/theos/sdks/archive/master.zip
          unzip sdks.zip -d $HOME/
          export THEOS=$HOME/theos
          export SDKROOT=$HOME/sdks-master/iPhoneOS14.5.sdk
          echo "export THEOS=$HOME/theos" >> ~/.bashrc
          echo "export SDKROOT=$HOME/sdks-master/iPhoneOS14.5.sdk" >> ~/.bashrc
      - name: Build package
        run: |
          export THEOS=$HOME/theos
          export SDKROOT=$HOME/sdks-master/iPhoneOS14.5.sdk
          make package FINALPACKAGE=1
      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: modded-ipa
          path: packages/*.ipa
